apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: sobolobo-com-tls
spec:
  secretName: sobolobo-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: sobolobo.com
  dnsNames:
    - sobolobo.com
    - www.sobolobo.com
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - sobolobo.com
          - www.sobolobo.com
